version: "3.1"

services:
    ioserver:
        build:
            context: .
            dockerfile: ./dev.Dockerfile
        ports:
            - 5002:5002
        networks:
            - node
        image: librarian-ioserver-dev
        volumes:
            - ./src:/root/src/node/src
            - ./.env:/root/src/node/.env
        environment:
            DB_HOST: mongo
            DB_NAME: librariannode
            REDIS_HOST: redis
            SENDGRID_API_KEY: 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

    mongo:
        image: mongo
        ports:
            - 27017:27017
        networks:
            - node
        restart: always

    redis:
        image: redis
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
        networks:
            - node
        restart: always

networks:
    node:
