version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
    image: fptu-librarian-webapp
    container_name: fptu-librarian-webapp
    volumes:
      - ./public:/root/src/app/public
      - ./src:/root/src/app/src
      - ./.env:/root/src/app/src/.env
    tty: true
