version: "3.4"
services:
  redisbc:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redisbc-data:/data
    networks:
      - node
    restart: always

  redisio:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6380:6379
    volumes:
      - redisio-data:/data
    networks:
      - node
    restart: always

  mongodbbc:
    image: mongo
    ports:
        - 27018:27017
    volumes:
      - mongodbbc-data:/data/db
    networks:
      - node
    restart: always
  
  mongodbio:
    image: mongo
    ports:
        - 27019:27017
    volumes:
      - mongodbio-data:/data/db
    networks:
      - node
    restart: always

  webapp:
    build:
      context: ./webapp
      dockerfile: ./dev.Dockerfile
    ports:
      - 3000:3000
    image: librarian-webapp-dev
    volumes:
      - ./webapp/src:/root/src/app/src
      - ./webapp/public:/root/src/app/public
      - ./webapp/.env:/root/src/app/.env
    environment:
      VUE_APP_API_BASE_URL: http://localhost:5000
      VUE_APP_API_BETA_URL: http://localhost:5002
      VUE_APP_SOCKET_URL: http://localhost:5002

  visualizeapp:
    build:
      context: ./visualizeapp
      dockerfile: ./dev.Dockerfile
    ports:
      - 3001:3000
    image: librarian-visualizeapp-dev
    volumes:
      - ./visualizeapp/src:/root/src/app/src
      - ./visualizeapp/public:/root/src/app/public

  pairworker:
    build:
      context: ./pairworker
      dockerfile: ./dev.Dockerfile
    ports:
      - 5100:5100
    networks:
      - node
    depends_on:
      - mongodbbc
    image: librarian-pairworker-dev
    environment:
      MONGODB: mongodbbc

  bcserver:
    build:
      context: ./bcserver
      dockerfile: ./dev.Dockerfile
    ports:
      - 5000:5000
    networks:
      - node
    depends_on:
      - mongodbbc
      - redisbc
    image: librarian-bcserver-dev
    volumes:
      - ./bcserver/src:/root/src/node/src
    environment:
      DB_HOST: mongodbbc
      DB_NAME: librarianblockchain
      REDIS_HOST: redisbc
      BIGCHAIN_HOST: http://host.docker.internal:9984/api/v1/
      # BigchainDB Local is http://host.docker.internal:9984/api/v1/ - hosted is https://testnet.fuchain.fptu.tech/api/v1/
      PUBLIC_KEY: CCth57e7618EfhcmWHyTAV4rvvk9fr1TVrwVmVmBkkqz
      PRIVATE_KEY: FFrKcgQfbhMWFgqgSSQkZPPNxwbbCMiJBTG3bk3a9xJA
      IO_HOST: http://ioserver:5002/api/v1
      PAIR_HOST: http://pairworker:5100

  ioserver:
    build:
      context: ./ioserver
      dockerfile: ./dev.Dockerfile
    ports:
      - 5002:5002
    networks:
      - node
    depends_on:
      - mongodbio
      - redisio
    image: librarian-ioserver-dev
    volumes:
      - ./ioserver/src:/root/src/node/src
    environment:
      DB_HOST: mongodbio
      DB_NAME: librariannode
      REDIS_HOST: redisio
      SENDGRID_API_KEY: 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

networks:
  node:

volumes:
  redisio-data:
  redisbc-data:
  mongodbbc-data:
  mongodbio-data: