version: "3"
services:
  redisbc:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redisbc-data:/data
    networks:
      - node
    deploy:
      placement:
        constraints: [node.role == manager]

  redisio:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6380:6379
    volumes:
      - redisio-data:/data
    networks:
      - node
    deploy:
      placement:
        constraints: [node.role == manager]

  mongodbbc:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodbbc-data:/data/db
    networks:
      - node
    deploy:
      placement:
        constraints: [node.role == manager]

  mongodbio:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - mongodbio-data:/data/db
    networks:
      - node
    deploy:
      placement:
        constraints: [node.role == manager]

  webapp:
    image: fptu/webapp:latest
    ports:
      - 3000:80
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  visualizeapp:
    image: fptu/visualizeapp:latest
    ports:
      - 3001:80
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  pairworker:
    image: fptu/pairworker:latest
    ports:
      - 5100:5100
    networks:
      - node
    depends_on:
      - mongodbbc
    environment:
      MONGODB: mongodbbc
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  bcserver:
    image: fptu/bcserver:latest
    ports:
      - 5000:5000
    networks:
      - node
    depends_on:
      - mongodbbc
      - redisbc
    environment:
      ENVIRONMENT: production
      DB_HOST: mongodbbc
      DB_NAME: librarianblockchain
      REDIS_HOST: redisbc
      BIGCHAIN_HOST: https://fuchain.fptu.tech/api/v1/
      PUBLIC_KEY: CCth57e7618EfhcmWHyTAV4rvvk9fr1TVrwVmVmBkkqz
      PRIVATE_KEY: FFrKcgQfbhMWFgqgSSQkZPPNxwbbCMiJBTG3bk3a9xJA
      IO_HOST: https://api.fptu.tech/io/api/v1
    deploy:
      replicas: 4
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  ioserver:
    image: fptu/ioserver:latest
    ports:
      - 5002:5002
    networks:
      - node
    depends_on:
      - mongodbio
      - redisio
    environment:
      ENVIRONMENT: production
      DB_HOST: mongodbio
      DB_NAME: librariannode
      REDIS_HOST: redisio
      SENDGRID_API_KEY: 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
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "1000:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

  queue-visualizer:
    image: fptu/queue-visualizer:latest
    ports:
      - "4567:4567"
    networks:
      - node
    depends_on:
      - redisbc
    deploy:
      replicas: 1

networks:
  node:

volumes:
  redisio-data:
  redisbc-data:
  mongodbbc-data:
  mongodbio-data:
