version: "3.4"
services:
  redisbc:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redisbc-data:/data
    networks:
      - node
    restart: always

  redisio:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6380:6379
    volumes:
      - redisio-data:/data
    networks:
      - node
    restart: always

  mongodbbc:
    image: mongo
    ports:
        - 27018:27017
    volumes:
      - mongodbbc-data:/data/db
    networks:
      - node
    restart: always
  
  mongodbio:
    image: mongo
    ports:
        - 27019:27017
    volumes:
      - mongodbio-data:/data/db
    networks:
      - node
    restart: always

  webapp:
    image: fptudev/webapp:latest
    ports:
      - 3000:3000
    volumes:
      - ./webapp/src:/root/src/app/src
      - ./webapp/public:/root/src/app/public
      - ./webapp/.env:/root/src/app/.env

  visualizeapp:
    image: fptudev/visualizeapp:latest
    ports:
      - 3001:3000
    volumes:
      - ./visualizeapp/src:/root/src/app/src
      - ./visualizeapp/public:/root/src/app/public

  pairworker:
    image: fptudev/pairworker:latest
    ports:
      - 5100:5100
    networks:
      - node
    depends_on:
      - mongodbbc
    environment:
      MONGODB: mongodbbc

  bcserver:
    image: fptudev/bcserver:latest
    ports:
      - 5000:5000
    networks:
      - node
    depends_on:
      - mongodbbc
      - redisbc
    volumes:
      - ./bcserver/src:/root/src/node/src
    environment:
      DB_HOST: mongodbbc
      DB_NAME: librarianblockchain
      REDIS_HOST: redisbc
      BIGCHAIN_HOST: http://dockerhost:9984/api/v1/
      PUBLIC_KEY: CCth57e7618EfhcmWHyTAV4rvvk9fr1TVrwVmVmBkkqz
      PRIVATE_KEY: FFrKcgQfbhMWFgqgSSQkZPPNxwbbCMiJBTG3bk3a9xJA
      IO_HOST: http://ioserver:5002/api/v1
      PAIR_HOST: http://pairworker:5100

  ioserver:
    image: fptudev/ioserver:latest
    ports:
      - 5002:5002
    networks:
      - node
    depends_on:
      - mongodbio
      - redisio
    volumes:
      - ./ioserver/src:/root/src/node/src
    environment:
      DB_HOST: mongodbio
      DB_NAME: librariannode
      REDIS_HOST: redisio
      SENDGRID_API_KEY: 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

  dockerhost:
    image: qoomon/docker-host
    networks:
      - node
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]

networks:
  node:

volumes:
  redisio-data:
  redisbc-data:
  mongodbbc-data:
  mongodbio-data: