version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    image: fptu-api-dev
    container_name: fptu-api-dev
    volumes:
      - ./src:/root/src/api/src
    tty: true
