
---
- name: Creating directories | yum
  file:
    path: "{{ item }}"
    state: directory
    mode: 0700
  with_items: "{{ directories }}"
  tags: [bigchaindb]

- name: Install dependencies | yum
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ dependencies_yum }}"
  tags: [bigchaindb]

- name: Install pip
  shell: "easy_install-3.5 pip"