---
- import_tasks: debian.yml
  when: stack_type|lower == "local" and (ansible_distribution|lower == "debian" or ansible_distribution|lower == "ubuntu")
  tags: [py36]

- import_tasks: centos.yml
  when: stack_type|lower == "local" and (ansible_distribution|lower == "centos" or ansible_distribution|lower == "red hat enterprise linux")
  tags: [py36]

- import_tasks: fedora.yml
  when: stack_type|lower == "local" and (ansible_distribution|lower == "fedora")
