apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nodeserver
  name: nodeserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nodeserver
    spec:
      containers:
      - env:
        - name: DB_DIALECT
          value: postgres
        - name: DB_HOST
          value: postgresn
        - name: DB_NAME
          value: node
        - name: DB_PASS
          value: capstone
        - name: DB_USER
          value: capstone
        - name: REDIS_HOST
          value: redis
        image: fptu/librarian-nodeserver:latest
        name: nodeserver
        ports:
        - containerPort: 5002
        resources: {}
      restartPolicy: Always
status: {}
