apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  containers:
  - env:
    - name: PGADMIN_DEFAULT_EMAIL
      value: admin@fptu.tech
    - name: PGADMIN_DEFAULT_PASSWORD
      value: capstone
    image: dpage/pgadmin4
    name: pgadmin
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}
