apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webapp
  name: webapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webapp
    spec:
      containers:
      - env:
        - name: VUE_APP_API_BASE_URL
          value: https://lapi.fptu.tech
        - name: VUE_APP_API_BETA_URL
          value: https://napi.fptu.tech
        - name: VUE_APP_SOCKET_URL
          value: http://napi.fptu.tech
        image: fptu/librarian-webapp:latest
        name: webapp
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
