version: "3"
services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    container_name: librarian-redis-dev
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - node
    restart: always

  mongodbbc:
    image: mongo
    container_name: librarian-mongodbbc-dev
    ports:
        - 27018:27017
    volumes:
      - mongodbbc-data:/data/db
    networks:
      - node
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: capstone
        MONGO_INITDB_ROOT_PASSWORD: capstone
  
  mongodbio:
    image: mongo
    container_name: librarian-mongodbio-dev
    ports:
        - 27019:27017
    volumes:
      - mongodbio-data:/data/db
    networks:
      - node
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: capstone
        MONGO_INITDB_ROOT_PASSWORD: capstone

  webapp:
    build:
      context: ./WebApp
      dockerfile: ./dev.Dockerfile
    ports:
      - 3000:3000
    image: librarian-webapp-dev
    container_name: librarian-webapp-dev
    volumes:
      - ./WebApp/src:/root/src/app/src
      - ./WebApp/public:/root/src/app/public
      - ./WebApp/.env:/root/src/app/.env
    environment:
      VUE_APP_API_BASE_URL: http://localhost:5000
      VUE_APP_API_BETA_URL: http://localhost:5002
      VUE_APP_SOCKET_URL: http://localhost:5002

  visualizeapp:
    build:
      context: ./VisualizeApp
      dockerfile: ./dev.Dockerfile
    ports:
      - 3001:3000
    image: librarian-visualizeapp-dev
    container_name: librarian-visualizeapp-dev
    volumes:
      - ./VisualizeApp/src:/root/src/app/src
      - ./VisualizeApp/public:/root/src/app/public

  bcserver:
    build:
      context: ./BlockchainServer
      dockerfile: ./dev.Dockerfile
    ports:
      - 5000:5000
    networks:
      - node
    depends_on:
      - mongodbbc
      - redis
    image: librarian-bcserver-dev
    container_name: librarian-bcserver-dev
    volumes:
      - ./BlockchainServer/src:/root/src/node/src
      - ./BlockchainServer/.env:/root/src/node/.env
    environment:
      DB_HOST: mongodbbc
      DB_USER: capstone
      DB_PASS: capstone
      DB_NAME: librariannode
      REDIS_HOST: redis

  ioserver:
    build:
      context: ./IOServer
      dockerfile: ./dev.Dockerfile
    ports:
      - 5002:5002
    networks:
      - node
    depends_on:
      - mongodbio
      - redis
    image: librarian-ioserver-dev
    container_name: librarian-ioserver-dev
    volumes:
      - ./IOServer/src:/root/src/node/src
      - ./IOServer/.env:/root/src/node/.env
    environment:
      DB_HOST: mongodbio
      DB_USER: capstone
      DB_PASS: capstone
      DB_NAME: librariannode
      REDIS_HOST: redis
      SENDGRID_API_KEY: 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

networks:
  node:

volumes:
  redis-data:
  mongodbbc-data:
  mongodbio-data: