version: "3"
services:
  redisbc:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redisbc-data:/data
    networks:
      - node
    restart: always

  redisio:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - 6380:6379
    volumes:
      - redisio-data:/data
    networks:
      - node
    restart: always

  mongodbbc:
    image: mongo
    ports:
        - 27017:27017
    volumes:
      - mongodbbc-data:/data/db
    networks:
      - node
    restart: always
  
  mongodbio:
    image: mongo
    ports:
        - 27018:27017
    volumes:
      - mongodbio-data:/data/db
    networks:
      - node
    restart: always

  webapp:
    build:
      context: ./WebApp
      dockerfile: ./dev.Dockerfile
    ports:
      - 3000:3000
    image: librarian-webapp-dev
    volumes:
      - ./WebApp/src:/root/src/app/src
      - ./WebApp/public:/root/src/app/public
      - ./WebApp/.env:/root/src/app/.env
    environment:
      VUE_APP_API_BASE_URL: http://localhost:5000
      VUE_APP_API_BETA_URL: http://localhost:5002
      VUE_APP_SOCKET_URL: http://localhost:5002

  visualizeapp:
    build:
      context: ./VisualizeApp
      dockerfile: ./dev.Dockerfile
    ports:
      - 3001:3000
    image: librarian-visualizeapp-dev
    volumes:
      - ./VisualizeApp/src:/root/src/app/src
      - ./VisualizeApp/public:/root/src/app/public

  pairworker:
    build:
      context: ./PairWorker
      dockerfile: ./dev.Dockerfile
    ports:
      - 5100:5100
    networks:
      - node
    depends_on:
      - mongodbbc
    image: librarian-pairworker-dev
    environment:
      MONGODB: mongodbbc

  bcserver:
    build:
      context: ./BlockchainServer
      dockerfile: ./dev.Dockerfile
    ports:
      - 5000:5000
    networks:
      - node
    depends_on:
      - mongodbbc
      - redisbc
    image: librarian-bcserver-dev
    volumes:
      - ./BlockchainServer/src:/root/src/node/src
    environment:
      DB_HOST: mongodbbc
      DB_NAME: librarianblockchain
      REDIS_HOST: redisbc
      BIGCHAIN_HOST: https://testnet.bigchain.fptu.tech/api/v1/
      PUBLIC_KEY: Y95FVZsm25rvRhCgV4wZ5NMNE3A3SdJGeKk6KBqroD9
      PRIVATE_KEY: CviuZeJhVuvtUc25BUuUDUmU8nARFqpxYKDGQP61s4is

  ioserver:
    build:
      context: ./IOServer
      dockerfile: ./dev.Dockerfile
    ports:
      - 5002:5002
    networks:
      - node
    depends_on:
      - mongodbio
      - redisio
    image: librarian-ioserver-dev
    volumes:
      - ./IOServer/src:/root/src/node/src
    environment:
      DB_HOST: mongodbio
      DB_NAME: librariannode
      REDIS_HOST: redis
      SENDGRID_API_KEY: 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

networks:
  node:

volumes:
  redisio-data:
  redisbc-data:
  mongodbbc-data:
  mongodbio-data: