version: "3"
services:
  api:
    build:
      context: ./WebServer
    expose:
      - 8080
    ports:
      - 8080:8080
    image: server-dev
    container_name: server-dev
    volumes:
      - ./WebServer/src:/root/src/api/src
    tty: true
    networks:
      - backend

  web:
    build:
      context: ./WebApp
    expose:
      - 3000
    ports:
      - 3000:3000
    image: web-dev
    container_name: web-dev
    volumes:
      - ./WebApp/src:/root/src/app/src
      - ./WebApp/public:/root/src/app/public
    tty: true
    networks:
      - backend
