version: "3.1"

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: capstone
            MONGO_INITDB_ROOT_PASSWORD: capstone

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: capstone
            ME_CONFIG_MONGODB_ADMINPASSWORD: capstone

    redis:
        image: redis
        command: redis-server --appendonly yes
        ports:
            - 6379:6379
        restart: always
